"""
Django settings for demo project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_*x6=mwcz7ac2r%ci98t_utbbnyakw*2elv2!!wady&$knd=fm'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ImputePilot_api', 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'demo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'demo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/0"

CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]

CELERY_TASK_TRACK_STARTED = True


# ========== Baseline External Runners (default local config) ==========
# These defaults allow multi-env baseline runners to work without exporting
# env vars in every shell. You can still override any value via environment vars.
CONDA_HOME = os.getenv("CONDA_HOME", str(Path.home() / "anaconda3"))
FLAML_ENV_NAME = os.getenv("FLAML_ENV_NAME", "ImputePilot-flaml")
TUNE_ENV_NAME = os.getenv("TUNE_ENV_NAME", "ImputePilot-tune")
RAHA_ENV_NAME = os.getenv("RAHA_ENV_NAME", "ImputePilot-raha")
AUTOFOLIO_ENV_NAME = os.getenv("AUTOFOLIO_ENV_NAME", "ImputePilot-autofolio")

BASELINE_RUNNERS_DIR = os.getenv(
    "BASELINE_RUNNERS_DIR",
    str(BASE_DIR / "baseline_runners"),
)
FLAML_VENV_PY = os.getenv(
    "FLAML_VENV_PY",
    f"{CONDA_HOME}/envs/{FLAML_ENV_NAME}/bin/python",
)
TUNE_VENV_PY = os.getenv(
    "TUNE_VENV_PY",
    f"{CONDA_HOME}/envs/{TUNE_ENV_NAME}/bin/python",
)
RAHA_VENV_PY = os.getenv(
    "RAHA_VENV_PY",
    f"{CONDA_HOME}/envs/{RAHA_ENV_NAME}/bin/python",
)
AUTOFOLIO_VENV_PY = os.getenv(
    "AUTOFOLIO_VENV_PY",
    f"{CONDA_HOME}/envs/{AUTOFOLIO_ENV_NAME}/bin/python",
)


# ========== Labeling External Runner (DL algorithms) ==========
DL_LABEL_ENV_NAME = os.getenv("DL_LABEL_ENV_NAME", "ImputePilot-labeldl311-mpin")
LABELING_RUNNERS_DIR = os.getenv(
    "LABELING_RUNNERS_DIR",
    str(BASE_DIR / "labeling_runners"),
)
DL_LABEL_VENV_PY = os.getenv(
    "DL_LABEL_VENV_PY",
    f"{CONDA_HOME}/envs/{DL_LABEL_ENV_NAME}/bin/python",
)
DL_LABEL_RUNNER_SCRIPT = os.getenv(
    "DL_LABEL_RUNNER_SCRIPT",
    str(Path(LABELING_RUNNERS_DIR) / "dl_benchmark_runner.py"),
)
DL_LABEL_ALGO = os.getenv("DL_LABEL_ALGO", "brits")
DL_LABEL_DEVICE = os.getenv("DL_LABEL_DEVICE", "cpu")
DL_LABEL_CELERY_QUEUE = os.getenv("DL_LABEL_CELERY_QUEUE", "dl_gpu")
DL_LABEL_TIMEOUT_SEC = int(os.getenv("DL_LABEL_TIMEOUT_SEC", "1800"))
DL_IMPUTE_ALGOS = os.getenv("DL_IMPUTE_ALGOS", "brits,deepmvi,mrnn,mpin,iim")
